import { TFile, Vault, Notice, normalizePath } from 'obsidian';
import { FoodItem } from '../types/nutrition';
import { PluginSettings } from '../types/settings';
import { FileUtils } from './file-utils';
import { LayoutGenerator } from './layout-generator';
import { ContentParser } from './content-parser';

export class FoodLogManager {
  private fileUtils: FileUtils;
  private layoutGenerator: LayoutGenerator;
  private contentParser: ContentParser;

  constructor(private vault: Vault, private settings: PluginSettings) {
    this.fileUtils = new FileUtils(vault);
    this.layoutGenerator = new LayoutGenerator(settings);
    this.contentParser = new ContentParser();
  }

  async createOrUpdateFoodLog(foodItems: FoodItem[], replaceEntry?: { food: string, quantity: string, calories: number, protein: number, carbs: number, fat: number }): Promise<{ createdNewFile: boolean; filePath: string }> {
    const today = this.fileUtils.getTodayString();
    const logPath = normalizePath(`${this.settings.logStoragePath}/${today}.md`);

    try {
      await this.fileUtils.ensureDirectoryExists(this.settings.logStoragePath);

      const existingFile = this.vault.getAbstractFileByPath(logPath);
      let createdNewFile = false;

      if (existingFile instanceof TFile) {
        if (replaceEntry) {
          await this.replaceInExistingLog(existingFile, foodItems, replaceEntry);
        } else {
          await this.appendToExistingLog(existingFile, foodItems);
        }
      } else {
        await this.createNewFoodLog(logPath, foodItems);
        createdNewFile = true;
      }

      if (replaceEntry) {
        new Notice(`✏️ Food entry replaced in: ${today}.md`);
      } else {
        new Notice(`Food log updated: ${today}.md`);
      }

      return { createdNewFile, filePath: logPath };
    } catch (error) {
      console.error('Error creating/updating food log:', error);
      throw new Error(`Failed to save food log: ${error.message}`);
    }
  }

  async deleteFoodLogItem(itemToDelete: { food: string, quantity: string, calories: number, protein: number, carbs: number, fat: number }): Promise<void> {
    const today = this.fileUtils.getTodayString();
    const logPath = normalizePath(`${this.settings.logStoragePath}/${today}.md`);
    
    try {
      const existingFile = this.vault.getAbstractFileByPath(logPath);
      
      if (!(existingFile instanceof TFile)) {
        throw new Error('Food log file not found for today');
      }
      
      await this.vault.process(existingFile, (content) => {
        const deleteResult = this.contentParser.deleteCardFromContent(content, itemToDelete);
        
        if (!deleteResult.success) {
          throw new Error('Item not found in food log');
        }
        
        return this.recalculateTotals(deleteResult.content);
      });
    } catch (error) {
      console.error('Error deleting food log item:', error);
      throw new Error(`Failed to delete food log item: ${error.message}`);
    }
  }

  private async createNewFoodLog(path: string, foodItems: FoodItem[]): Promise<void> {
    const today = this.fileUtils.getTodayString();
    const totals = this.contentParser.calculateTotals(foodItems);
    
    let content = `# 🍽️ Food Log ${today}\n\n`;
    content += `## 🥗 Today's Meals\n\n`;
    content += this.layoutGenerator.generateCardLayout(foodItems);
    content += '\n<div class="food-placeholder"></div>\n\n';
    content += this.layoutGenerator.generateCTAButtons('foodlog');
    content += this.layoutGenerator.generateDailySummary(totals);
    content += '\n\n---\n\n';
    content += '*✨ Generated by AI Nutrition Tracker Plugin*\n';
    
    await this.vault.create(path, content);
  }

  private async appendToExistingLog(file: TFile, foodItems: FoodItem[]): Promise<void> {
    const newCard = this.layoutGenerator.generateCardLayout(foodItems);
    const placeholder = '<div class="food-placeholder"></div>';
    
    await this.vault.process(file, (content) => {
      const placeholderIndex = content.indexOf(placeholder);
      
      if (placeholderIndex !== -1) {
        const updatedContent = content.replace(
          placeholder,
          newCard + '\n' + placeholder
        );
        return this.recalculateTotals(updatedContent);
      } else {
        const ctaButtonIndex = content.indexOf('class="nutrition-add-cta-btn"');
        if (ctaButtonIndex !== -1) {
          const insertPosition = content.lastIndexOf('<div', ctaButtonIndex);
          const beforeInsert = content.substring(0, insertPosition);
          const afterInsert = content.substring(insertPosition);
          const updatedContent = beforeInsert + newCard + '\n' + placeholder + '\n\n' + afterInsert;
          return this.recalculateTotals(updatedContent);
        }
      }
      
      return content;
    });
  }

  private async replaceInExistingLog(file: TFile, newFoodItems: FoodItem[], originalEntry: { food: string, quantity: string, calories: number, protein: number, carbs: number, fat: number }): Promise<void> {
    const newCardContent = this.layoutGenerator.generateCardLayout(newFoodItems);
    
    try {
      await this.vault.process(file, (content) => {
        const replacement = this.contentParser.replaceCardInPosition(content, originalEntry, newCardContent);
        
        if (replacement.success) {
          return this.recalculateTotals(replacement.content);
        } else {
          throw new Error('Could not find card to replace');
        }
      });
    } catch (error) {
      if (error.message === 'Could not find card to replace') {
        await this.appendToExistingLog(file, newFoodItems);
      } else {
        throw error;
      }
    }
  }


  private recalculateTotals(content: string): string {
    const foodItems = this.contentParser.extractFoodItemsFromContent(content);
    const totals = this.contentParser.calculateTotals(foodItems);
    
    const newSummary = this.layoutGenerator.generateDailySummary(totals);
    
    // Find the summary card
    const summaryStart = content.indexOf('<div class="ntr-summary-card');
    
    if (summaryStart !== -1) {
      // Find the matching closing div for the summary card
      const summaryBounds = this.contentParser.findCardBounds(content, summaryStart);
      
      if (summaryBounds.success) {
        // Replace existing summary
        const beforeSummary = content.substring(0, summaryStart);
        const afterSummary = content.substring(summaryBounds.endIndex);
        return beforeSummary + newSummary.trim() + afterSummary;
      }
    }
    
    // No summary exists, add it (this shouldn't happen with placeholder approach)
    const ctaButtons = this.layoutGenerator.generateCTAButtons('foodlog');
    return content.trim() + '\n\n' + ctaButtons.trim() + '\n\n' + newSummary.trim() + '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n';
  }
} 