import { TFile, Notice, normalizePath } from 'obsidian';
import { FoodItem, FoodLogEntry, NutritionGoals } from '../../types/nutrition';
import { PluginContext } from '../../types/plugin-context';
import * as FileUtils from '../file';
import * as LayoutGenerator from '../layout-generator';
import * as ContentParser from '../content-parser';
import { readFoodLog, writeFoodLog } from './food-log-storage';

function toFoodLogEntries(items: FoodItem[]): FoodLogEntry[] {
  return items.map(item => ({ ...item, id: item.id ?? FileUtils.generateEntryId() }));
}

function renderGeneratedRegion(entries: FoodLogEntry[], goals: NutritionGoals): string {
  const totals = ContentParser.calculateTotals(entries);

  let content = `## 🥗 Today's Meals\n\n`;
  content += LayoutGenerator.generateCardLayout(entries, goals, 'foodlog');
  content += LayoutGenerator.generateDailySummary(totals, goals);

  return content;
}

async function writeFoodLogNote(
  ctx: PluginContext,
  existingFile: TFile | null,
  logPath: string,
  date: string,
  entries: FoodLogEntry[]
): Promise<void> {
  const goals = ctx.settings.nutritionGoals;
  const generatedRegion = renderGeneratedRegion(entries, goals);

  if (existingFile) {
    await ctx.vault.process(existingFile, (content) => ContentParser.replaceMarkedRegion(content, generatedRegion));
    return;
  }

  await FileUtils.ensureDirectoryExists(ctx, ctx.settings.logStoragePath);

  const header = `# 🍽️ Food Log ${date}\n\n`;
  const footer = '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n';
  const content = header + ContentParser.wrapInMarkers(generatedRegion) + footer;

  await ctx.vault.create(logPath, content);
}

export async function createOrUpdateFoodLog(
  ctx: PluginContext,
  foodItems: FoodItem[],
  replaceEntryId?: string
): Promise<{ createdNewFile: boolean; filePath: string }> {
  const today = FileUtils.getTodayString();
  const logPath = normalizePath(`${ctx.settings.logStoragePath}/${today}.md`);

  try {
    const log = await readFoodLog(ctx.vault, ctx.settings, today);

    if (replaceEntryId) {
      const index = log.entries.findIndex(entry => entry.id === replaceEntryId);
      const replacementItem = foodItems[0];

      if (index === -1 || !replacementItem) {
        throw new Error('Entry not found in food log');
      }

      log.entries[index] = { ...replacementItem, id: replaceEntryId };
    } else {
      log.entries.push(...toFoodLogEntries(foodItems));
    }

    await writeFoodLog(ctx.vault, ctx.settings, log);

    const existingFile = ctx.vault.getAbstractFileByPath(logPath);
    const createdNewFile = !(existingFile instanceof TFile);

    await writeFoodLogNote(ctx, existingFile instanceof TFile ? existingFile : null, logPath, today, log.entries);

    if (replaceEntryId) {
      new Notice(`✏️ Food entry replaced in: ${today}.md`);
    } else {
      new Notice(`Food log updated: ${today}.md`);
    }

    return { createdNewFile, filePath: logPath };
  } catch (error) {
    console.error('Error creating/updating food log:', error);
    throw new Error(`Failed to save food log: ${error.message}`);
  }
}

export async function deleteFoodLogItem(ctx: PluginContext, entryId: string): Promise<void> {
  const today = FileUtils.getTodayString();
  const logPath = normalizePath(`${ctx.settings.logStoragePath}/${today}.md`);

  try {
    const log = await readFoodLog(ctx.vault, ctx.settings, today);
    const index = log.entries.findIndex(entry => entry.id === entryId);

    if (index === -1) {
      throw new Error('Item not found in food log');
    }

    log.entries.splice(index, 1);
    await writeFoodLog(ctx.vault, ctx.settings, log);

    const existingFile = ctx.vault.getAbstractFileByPath(logPath);
    if (existingFile instanceof TFile) {
      await writeFoodLogNote(ctx, existingFile, logPath, today, log.entries);
    }
  } catch (error) {
    console.error('Error deleting food log item:', error);
    throw new Error(`Failed to delete food log item: ${error.message}`);
  }
}
