import { TFile, Notice, normalizePath } from 'obsidian';
import { FoodItem } from '../../types/nutrition';
import { PluginContext } from '../../types/plugin-context';
import * as FileUtils from '../file';
import * as LayoutGenerator from '../layout-generator';
import * as ContentParser from '../content-parser';

export async function createOrUpdateFoodLog(
  ctx: PluginContext,
  foodItems: FoodItem[],
  replaceEntry?: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<{ createdNewFile: boolean; filePath: string }> {
  const today = FileUtils.getTodayString();
  const logPath = normalizePath(`${ctx.settings.logStoragePath}/${today}.md`);

  try {
    await FileUtils.ensureDirectoryExists(ctx, ctx.settings.logStoragePath);

    const existingFile = ctx.vault.getAbstractFileByPath(logPath);
    let createdNewFile = false;

    if (existingFile instanceof TFile) {
      if (replaceEntry) {
        await replaceInExistingLog(ctx, existingFile, foodItems, replaceEntry);
      } else {
        await appendToExistingLog(ctx, existingFile, foodItems);
      }
    } else {
      await createNewFoodLog(ctx, logPath, foodItems);
      createdNewFile = true;
    }

    if (replaceEntry) {
      new Notice(`✏️ Food entry replaced in: ${today}.md`);
    } else {
      new Notice(`Food log updated: ${today}.md`);
    }

    return { createdNewFile, filePath: logPath };
  } catch (error) {
    console.error('Error creating/updating food log:', error);
    throw new Error(`Failed to save food log: ${error.message}`);
  }
}

export async function deleteFoodLogItem(
  ctx: PluginContext,
  itemToDelete: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<void> {
  const today = FileUtils.getTodayString();
  const logPath = normalizePath(`${ctx.settings.logStoragePath}/${today}.md`);

  try {
    const existingFile = ctx.vault.getAbstractFileByPath(logPath);

    if (!(existingFile instanceof TFile)) {
      throw new Error('Food log file not found for today');
    }

    await ctx.vault.process(existingFile, (content) => {
      const deleteResult = ContentParser.deleteCardFromContent(content, itemToDelete);

      if (!deleteResult.success) {
        throw new Error('Item not found in food log');
      }

      return recalculateTotals(ctx, deleteResult.content);
    });
  } catch (error) {
    console.error('Error deleting food log item:', error);
    throw new Error(`Failed to delete food log item: ${error.message}`);
  }
}

async function createNewFoodLog(ctx: PluginContext, path: string, foodItems: FoodItem[]): Promise<void> {
  const goals = ctx.settings.nutritionGoals;

  const today = FileUtils.getTodayString();
  const totals = ContentParser.calculateTotals(foodItems);

  let content = `# 🍽️ Food Log ${today}\n\n`;
  content += `## 🥗 Today's Meals\n\n`;
  content += LayoutGenerator.generateCardLayout(foodItems, goals);
  content += '\n<div class="food-placeholder"></div>\n\n';
  content += LayoutGenerator.generateCTAButtons('foodlog');
  content += LayoutGenerator.generateDailySummary(totals, goals);
  content += '\n\n---\n\n';
  content += '*✨ Generated by AI Nutrition Tracker Plugin*\n';

  await ctx.vault.create(path, content);
}

async function appendToExistingLog(ctx: PluginContext, file: TFile, foodItems: FoodItem[]): Promise<void> {
  const goals = ctx.settings.nutritionGoals;
  const newCard = LayoutGenerator.generateCardLayout(foodItems, goals);
  const placeholder = '<div class="food-placeholder"></div>';

  await ctx.vault.process(file, (content) => {
    const placeholderIndex = content.indexOf(placeholder);

    if (placeholderIndex !== -1) {
      const updatedContent = content.replace(placeholder, newCard + '\n' + placeholder);
      return recalculateTotals(ctx, updatedContent);
    } else {
      const ctaButtonIndex = content.indexOf('class="nutrition-add-cta-btn"');
      if (ctaButtonIndex !== -1) {
        const insertPosition = content.lastIndexOf('<div', ctaButtonIndex);
        const beforeInsert = content.substring(0, insertPosition);
        const afterInsert = content.substring(insertPosition);
        const updatedContent = beforeInsert + newCard + '\n' + placeholder + '\n\n' + afterInsert;
        return recalculateTotals(ctx, updatedContent);
      }
    }

    return content;
  });
}

async function replaceInExistingLog(
  ctx: PluginContext,
  file: TFile,
  newFoodItems: FoodItem[],
  originalEntry: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<void> {
  const goals = ctx.settings.nutritionGoals;
  const newCardContent = LayoutGenerator.generateCardLayout(newFoodItems, goals);

  try {
    await ctx.vault.process(file, (content) => {
      const replacement = ContentParser.replaceCardInPosition(content, originalEntry, newCardContent);

      if (replacement.success) {
        return recalculateTotals(ctx, replacement.content);
      } else {
        throw new Error('Could not find card to replace');
      }
    });
  } catch (error) {
    if (error.message === 'Could not find card to replace') {
      await appendToExistingLog(ctx, file, newFoodItems);
    } else {
      throw error;
    }
  }
}

function recalculateTotals(ctx: PluginContext, content: string): string {
  const goals = ctx.settings.nutritionGoals;

  const foodItems = ContentParser.extractFoodItemsFromContent(content);
  const totals = ContentParser.calculateTotals(foodItems);

  const newSummary = LayoutGenerator.generateDailySummary(totals, goals);

  // Find the summary card
  const summaryStart = content.indexOf('<div class="ntr-summary-card');

  if (summaryStart !== -1) {
    // Find the matching closing div for the summary card
    const summaryBounds = ContentParser.findCardBounds(content, summaryStart);

    if (summaryBounds.success) {
      // Replace existing summary
      const beforeSummary = content.substring(0, summaryStart);
      const afterSummary = content.substring(summaryBounds.endIndex);
      return beforeSummary + newSummary.trim() + afterSummary;
    }
  }

  // No summary exists, add it (this shouldn't happen with placeholder approach)
  const ctaButtons = LayoutGenerator.generateCTAButtons('foodlog');
  return (
    content.trim() +
    '\n\n' +
    ctaButtons.trim() +
    '\n\n' +
    newSummary.trim() +
    '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n'
  );
}
