import { Vault, TFile, normalizePath } from 'obsidian';
import { PluginSettings } from '../../types/settings';
import { FoodLogEntry, NutritionGoals } from '../../types/nutrition';
import * as FileUtils from '../file';
import * as LayoutGenerator from '../layout-generator';
import * as ContentParser from '../content-parser';
import * as LegacyParser from '../legacy/parser';
import { writeFoodLog } from './food-log-storage';

const DAILY_LOG_FILENAME = /^(\d{4}-\d{2}-\d{2})\.md$/;

function renderGeneratedRegion(entries: FoodLogEntry[], goals: NutritionGoals): string {
  const totals = ContentParser.calculateTotals(entries);

  let content = `## 🥗 Today's Meals\n\n`;
  content += LayoutGenerator.generateCardLayout(entries, goals, 'foodlog');
  content += LayoutGenerator.generateDailySummary(totals, goals);

  return content;
}

async function ensureBackup(vault: Vault, settings: PluginSettings, date: string, originalContent: string): Promise<void> {
  const backupDir = normalizePath(`${settings.logStoragePath}/.data`);
  if (!vault.getAbstractFileByPath(backupDir)) {
    await vault.createFolder(backupDir);
  }

  const backupPath = normalizePath(`${backupDir}/backup-${date}.md`);
  if (!vault.getAbstractFileByPath(backupPath)) {
    await vault.create(backupPath, originalContent);
  }
}

function findLegacyLogFiles(vault: Vault, settings: PluginSettings): TFile[] {
  return vault.getFiles().filter(file => {
    if (!DAILY_LOG_FILENAME.test(file.name)) return false;
    return file.path === normalizePath(`${settings.logStoragePath}/${file.name}`);
  });
}

export async function migrateFoodLogsToV3(
  vault: Vault,
  settings: PluginSettings
): Promise<{ migrated: boolean; count: number }> {
  if (settings.dataVersion === 3) {
    return { migrated: false, count: 0 };
  }

  const logFiles = findLegacyLogFiles(vault, settings);
  let migratedCount = 0;

  for (const file of logFiles) {
    const content = await vault.read(file);

    if (content.includes(ContentParser.NTR_MARKER_BEGIN)) {
      // Already in the new format — a previous, interrupted migration run got this far.
      continue;
    }

    const dateMatch = file.name.match(DAILY_LOG_FILENAME);
    if (!dateMatch) continue;
    const date = dateMatch[1];

    const legacyItems = LegacyParser.extractFoodItemsFromContent(content);
    const entries: FoodLogEntry[] = legacyItems.map(item => ({ ...item, id: FileUtils.generateEntryId() }));

    await ensureBackup(vault, settings, date, content);
    await writeFoodLog(vault, settings, { date, entries });

    const header = `# 🍽️ Food Log ${date}\n\n`;
    const footer = '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n';
    const newContent = header + ContentParser.wrapInMarkers(renderGeneratedRegion(entries, settings.nutritionGoals)) + footer;

    await vault.modify(file, newContent);
    migratedCount++;
  }

  settings.dataVersion = 3;

  return { migrated: migratedCount > 0, count: migratedCount };
}
