import { generateCardLayout, generateDailySummary, generateCTAButtons } from '../../layout-generator';
import { calculateTotals } from '../../content-parser';
import { migrateFoodLogsToV3 } from '../migrate-to-v3';
import { readFoodLog } from '../food-log-storage';
import { PluginSettings, DEFAULT_SETTINGS } from '../../../types/settings';
import { FoodItem } from '../../../types/nutrition';
import { createFakeVault } from '../../../test-utils/fake-vault';

// migrateFoodLogsToV3 mutates settings.dataVersion in place, so each test needs its own
// fresh settings object rather than a shared one.
function makeSettings(): PluginSettings {
  return { ...DEFAULT_SETTINGS, logStoragePath: 'tracker/health/food/log' };
}

// Reproduces the pre-3.0 note format: header, cards, CTA, daily summary, footer — no
// markers, no data-ntr-id. This is exactly what createNewFoodLog used to emit.
function legacyNote(date: string, items: FoodItem[]): string {
  const goals = DEFAULT_SETTINGS.nutritionGoals;
  const totals = calculateTotals(items);
  let content = `# 🍽️ Food Log ${date}\n\n`;
  content += `## 🥗 Today's Meals\n\n`;
  content += generateCardLayout(items, goals);
  content += '\n<div class="food-placeholder"></div>\n\n';
  content += generateCTAButtons('foodlog');
  content += generateDailySummary(totals, goals);
  content += '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n';
  return content;
}

describe('migrateFoodLogsToV3 — fixture vault', () => {
  test('migrates a simple day: JSON entries with fresh ids, note rewritten with markers, original backed up', async () => {
    const settings = makeSettings();
    const items: FoodItem[] = [
      { food: 'Oats', quantity: '50g', calories: 190, protein: 7, carbs: 33, fat: 3 },
      { food: 'Banana', quantity: '1 medium', calories: 105, protein: 1, carbs: 27, fat: 0 },
    ];
    const original = legacyNote('2026-07-01', items);
    const { vault, files } = createFakeVault({ 'tracker/health/food/log/2026-07-01.md': original });

    const result = await migrateFoodLogsToV3(vault, settings);

    expect(result).toEqual({ migrated: true, count: 1 });
    expect(settings.dataVersion).toBe(3);

    const log = await readFoodLog(vault, settings, '2026-07-01');
    expect(log.entries).toHaveLength(2);
    expect(log.entries.map(e => e.food)).toEqual(['Oats', 'Banana']);
    for (const entry of log.entries) {
      expect(typeof entry.id).toBe('string');
      expect(entry.id.length).toBeGreaterThan(0);
    }

    const backup = files.get('tracker/health/food/log/.data/backup-2026-07-01.md');
    expect(backup).toBe(original);

    const rewritten = files.get('tracker/health/food/log/2026-07-01.md')!;
    expect(rewritten).toContain('%% ntr:begin %%');
    expect(rewritten).toContain('%% ntr:end %%');
    expect(rewritten).toContain(`data-ntr-id="${log.entries[0].id}"`);
    expect(rewritten).toContain(`data-ntr-id="${log.entries[1].id}"`);
  });

  test('duplicate identical entries each get their own distinct fresh id', async () => {
    const settings = makeSettings();
    const duplicate: FoodItem = { food: 'Egg', quantity: '2 pcs', calories: 140, protein: 12, carbs: 1, fat: 10 };
    const original = legacyNote('2026-07-02', [duplicate, duplicate]);
    const { vault } = createFakeVault({ 'tracker/health/food/log/2026-07-02.md': original });

    await migrateFoodLogsToV3(vault, settings);

    const log = await readFoodLog(vault, settings, '2026-07-02');
    expect(log.entries).toHaveLength(2);
    expect(log.entries[0].id).not.toBe(log.entries[1].id);
  });

  test('special characters (quotes, regex metacharacters, unicode) survive migration', async () => {
    const settings = makeSettings();
    const items: FoodItem[] = [
      { food: 'Rice "Basmati"', quantity: '100g', calories: 130, protein: 2.7, carbs: 28, fat: 0.3 },
      { food: 'Chicken (grilled) + rice [200g]', quantity: '1 serving', calories: 300, protein: 30, carbs: 20, fat: 10 },
      { food: 'Käsespätzle 🧀', quantity: '1 Portion', calories: 480, protein: 18, carbs: 55, fat: 20 },
    ];
    const original = legacyNote('2026-07-03', items);
    const { vault } = createFakeVault({ 'tracker/health/food/log/2026-07-03.md': original });

    await migrateFoodLogsToV3(vault, settings);

    const log = await readFoodLog(vault, settings, '2026-07-03');
    expect(log.entries.map(e => e.food)).toEqual(items.map(i => i.food));
  });

  test('migrates multiple days in one run', async () => {
    const settings = makeSettings();
    const { vault } = createFakeVault({
      'tracker/health/food/log/2026-07-01.md': legacyNote('2026-07-01', [{ food: 'Oats', quantity: '50g', calories: 190, protein: 7, carbs: 33, fat: 3 }]),
      'tracker/health/food/log/2026-07-02.md': legacyNote('2026-07-02', [{ food: 'Egg', quantity: '2 pcs', calories: 140, protein: 12, carbs: 1, fat: 10 }]),
    });

    const result = await migrateFoodLogsToV3(vault, settings);

    expect(result).toEqual({ migrated: true, count: 2 });
  });

  test('ignores non-daily-log files in the log folder', async () => {
    const settings = makeSettings();
    const { vault, files } = createFakeVault({
      'tracker/health/food/log/README.md': '# Notes\n\nJust a regular note, not a daily log.',
    });

    const result = await migrateFoodLogsToV3(vault, settings);

    expect(result).toEqual({ migrated: false, count: 0 });
    expect(files.get('tracker/health/food/log/README.md')).toBe('# Notes\n\nJust a regular note, not a daily log.');
  });

  test('a fresh vault with no existing log notes completes cleanly and sets dataVersion', async () => {
    const settings = makeSettings();
    const { vault } = createFakeVault();

    const result = await migrateFoodLogsToV3(vault, settings);

    expect(result).toEqual({ migrated: false, count: 0 });
    expect(settings.dataVersion).toBe(3);
  });

  test('never runs twice — a second call is a no-op once dataVersion is 3', async () => {
    const settings = makeSettings();
    const items: FoodItem[] = [{ food: 'Oats', quantity: '50g', calories: 190, protein: 7, carbs: 33, fat: 3 }];
    const { vault, files } = createFakeVault({ 'tracker/health/food/log/2026-07-01.md': legacyNote('2026-07-01', items) });

    await migrateFoodLogsToV3(vault, settings);
    const afterFirstRun = files.get('tracker/health/food/log/2026-07-01.md');

    const secondResult = await migrateFoodLogsToV3(vault, settings);

    expect(secondResult).toEqual({ migrated: false, count: 0 });
    expect(files.get('tracker/health/food/log/2026-07-01.md')).toBe(afterFirstRun);
  });
});
