import { TFile, Vault, Notice, normalizePath } from 'obsidian';
import { FoodItem } from '../../types/nutrition';
import { PluginSettings } from '../../types/settings';
import { FileUtils } from '../file-utils';
import { LayoutGenerator } from '../layout-generator';
import { ContentParser } from '../content-parser';

export interface FoodLogDeps {
  vault: Vault;
  settings: PluginSettings;
}

export async function createOrUpdateFoodLog(
  deps: FoodLogDeps,
  foodItems: FoodItem[],
  replaceEntry?: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<{ createdNewFile: boolean; filePath: string }> {
  const fileUtils = new FileUtils(deps.vault);
  const today = fileUtils.getTodayString();
  const logPath = normalizePath(`${deps.settings.logStoragePath}/${today}.md`);

  try {
    await fileUtils.ensureDirectoryExists(deps.settings.logStoragePath);

    const existingFile = deps.vault.getAbstractFileByPath(logPath);
    let createdNewFile = false;

    if (existingFile instanceof TFile) {
      if (replaceEntry) {
        await replaceInExistingLog(deps, existingFile, foodItems, replaceEntry);
      } else {
        await appendToExistingLog(deps, existingFile, foodItems);
      }
    } else {
      await createNewFoodLog(deps, logPath, foodItems);
      createdNewFile = true;
    }

    if (replaceEntry) {
      new Notice(`✏️ Food entry replaced in: ${today}.md`);
    } else {
      new Notice(`Food log updated: ${today}.md`);
    }

    return { createdNewFile, filePath: logPath };
  } catch (error) {
    console.error('Error creating/updating food log:', error);
    throw new Error(`Failed to save food log: ${error.message}`);
  }
}

export async function deleteFoodLogItem(
  deps: FoodLogDeps,
  itemToDelete: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<void> {
  const fileUtils = new FileUtils(deps.vault);
  const today = fileUtils.getTodayString();
  const logPath = normalizePath(`${deps.settings.logStoragePath}/${today}.md`);

  try {
    const existingFile = deps.vault.getAbstractFileByPath(logPath);

    if (!(existingFile instanceof TFile)) {
      throw new Error('Food log file not found for today');
    }

    const contentParser = new ContentParser();

    await deps.vault.process(existingFile, (content) => {
      const deleteResult = contentParser.deleteCardFromContent(content, itemToDelete);

      if (!deleteResult.success) {
        throw new Error('Item not found in food log');
      }

      return recalculateTotals(deps, deleteResult.content);
    });
  } catch (error) {
    console.error('Error deleting food log item:', error);
    throw new Error(`Failed to delete food log item: ${error.message}`);
  }
}

async function createNewFoodLog(deps: FoodLogDeps, path: string, foodItems: FoodItem[]): Promise<void> {
  const fileUtils = new FileUtils(deps.vault);
  const layoutGenerator = new LayoutGenerator(deps.settings);
  const contentParser = new ContentParser();

  const today = fileUtils.getTodayString();
  const totals = contentParser.calculateTotals(foodItems);

  let content = `# 🍽️ Food Log ${today}\n\n`;
  content += `## 🥗 Today's Meals\n\n`;
  content += layoutGenerator.generateCardLayout(foodItems);
  content += '\n<div class="food-placeholder"></div>\n\n';
  content += layoutGenerator.generateCTAButtons('foodlog');
  content += layoutGenerator.generateDailySummary(totals);
  content += '\n\n---\n\n';
  content += '*✨ Generated by AI Nutrition Tracker Plugin*\n';

  await deps.vault.create(path, content);
}

async function appendToExistingLog(deps: FoodLogDeps, file: TFile, foodItems: FoodItem[]): Promise<void> {
  const layoutGenerator = new LayoutGenerator(deps.settings);
  const newCard = layoutGenerator.generateCardLayout(foodItems);
  const placeholder = '<div class="food-placeholder"></div>';

  await deps.vault.process(file, (content) => {
    const placeholderIndex = content.indexOf(placeholder);

    if (placeholderIndex !== -1) {
      const updatedContent = content.replace(placeholder, newCard + '\n' + placeholder);
      return recalculateTotals(deps, updatedContent);
    } else {
      const ctaButtonIndex = content.indexOf('class="nutrition-add-cta-btn"');
      if (ctaButtonIndex !== -1) {
        const insertPosition = content.lastIndexOf('<div', ctaButtonIndex);
        const beforeInsert = content.substring(0, insertPosition);
        const afterInsert = content.substring(insertPosition);
        const updatedContent = beforeInsert + newCard + '\n' + placeholder + '\n\n' + afterInsert;
        return recalculateTotals(deps, updatedContent);
      }
    }

    return content;
  });
}

async function replaceInExistingLog(
  deps: FoodLogDeps,
  file: TFile,
  newFoodItems: FoodItem[],
  originalEntry: { food: string; quantity: string; calories: number; protein: number; carbs: number; fat: number }
): Promise<void> {
  const layoutGenerator = new LayoutGenerator(deps.settings);
  const contentParser = new ContentParser();
  const newCardContent = layoutGenerator.generateCardLayout(newFoodItems);

  try {
    await deps.vault.process(file, (content) => {
      const replacement = contentParser.replaceCardInPosition(content, originalEntry, newCardContent);

      if (replacement.success) {
        return recalculateTotals(deps, replacement.content);
      } else {
        throw new Error('Could not find card to replace');
      }
    });
  } catch (error) {
    if (error.message === 'Could not find card to replace') {
      await appendToExistingLog(deps, file, newFoodItems);
    } else {
      throw error;
    }
  }
}

function recalculateTotals(deps: FoodLogDeps, content: string): string {
  const contentParser = new ContentParser();
  const layoutGenerator = new LayoutGenerator(deps.settings);

  const foodItems = contentParser.extractFoodItemsFromContent(content);
  const totals = contentParser.calculateTotals(foodItems);

  const newSummary = layoutGenerator.generateDailySummary(totals);

  // Find the summary card
  const summaryStart = content.indexOf('<div class="ntr-summary-card');

  if (summaryStart !== -1) {
    // Find the matching closing div for the summary card
    const summaryBounds = contentParser.findCardBounds(content, summaryStart);

    if (summaryBounds.success) {
      // Replace existing summary
      const beforeSummary = content.substring(0, summaryStart);
      const afterSummary = content.substring(summaryBounds.endIndex);
      return beforeSummary + newSummary.trim() + afterSummary;
    }
  }

  // No summary exists, add it (this shouldn't happen with placeholder approach)
  const ctaButtons = layoutGenerator.generateCTAButtons('foodlog');
  return (
    content.trim() +
    '\n\n' +
    ctaButtons.trim() +
    '\n\n' +
    newSummary.trim() +
    '\n\n---\n\n*✨ Generated by AI Nutrition Tracker Plugin*\n'
  );
}
